apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: cbp-12202-bug-fixed-test
on:
  workflow_dispatch:
jobs:
  cbp-12202-test-job:
    steps:
      # 1. Step with user-defined name (UI should show this name)
      - name: User-defined Step Name
        uses: cloudbees-io/checkout@v1

      # 2. Step with no name, but action has id (UI should show action's internal name)
      - uses: cloudbees-io/checkout@v1

      # 3. Step with no name, and action missing both id and name (UI should show fallback label)
      - uses: ./.cloudbees/my-fallback-action

      # 4. Step with user-defined name for configure-ecr-credentials (UI should show this name)
      - name: Configure container registry for ECR
        uses: cloudbees-io/configure-ecr-credentials@v1

      # 5. Step with no name, using configure-ecr-credentials (UI should show action's name if present)
      - uses: cloudbees-io/configure-ecr-credentials@v1
