apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: cbp-12202-bug-fixed-test
on:
  workflow_dispatch:
jobs:
  cbp-12202-test-job:
    steps:
      # 1. Step with user-defined name (UI should show this name)
      - name: Step 1: User-defined step name
        uses: cloudbees-io/checkout@v1

      # 2. Step with no name, but action has id (UI should show action's internal name)
      - name: Step 2: No step name, action has id
        uses: cloudbees-io/checkout@v1

      # 3. Step with no name, and action missing both id and name (UI should show fallback label)
      - name: Step 3: No step name, action missing id and name
        uses: ./.cloudbees/my-fallback-action
